version: '3.1'

services:

  graphy:
    build: .
    container_name: graphy
    # depends_on:
    #  - arangodb
    #  - zipkin
    # links:
    #  - zipkin
    volumes:
      - tmp/graphy/data:/Graphy/data

  arangodb:
    image: arangodb
    container_name: graphy_arangodb
    restart: on-failure
    environment:
      - ARANGO_ROOT_PASSWORD=password
      - name=arangodb-instance
    volumes:
      # Data persistency
      # sudo mkdir -p /tmp/graphy/arangodb; chown 472:472 /tmp/graphy/arangodb
      - /tmp/graphy/arangodb:/var/lib/arangodb3
    ports:
      - 8529:8529

  grafana:
    image: grafana/grafana:latest
    container_name: graphy_grafana
    # command: cfg:default.users.allow_sign_up=false
    ports:
      - 3000:3000
    env_file:
      - 'env.grafana'
    volumes:
      # Data persistency
      # sudo mkdir -p /tmp/graphy/grafana/data; chown 472:472 /tmp/graphy/grafana/data
      - /tmp/graphy/grafana/data:/var/lib/grafana

  opentsdb:
    image: petergrace/opentsdb-docker
    container_name: graphy_opentsdb
    environment:
      - WAITSECS=30
    ports:
      - 4242:4242
    volumes:
      # Data persistency
      # sudo mkdir -p /tmp/graphy/opentsdb/data; chown 472:472 /tmp/graphy/opentsdb/data
      - /tmp/graphy/opentsdb/data:/data/hbase
      # Config file
      - ./opentsdb.conf:/etc/opentsdb/opentsdb.conf

  zipkin:
    image: openzipkin/zipkin
    container_name: graphy_zipkin
    restart: always
    ports:
      - 9411:9411
