# Author: André Bento
version: 1

disable_existing_loggers: true

root:
  level: NOTSET
  handlers: [console]

loggers:
  InfoLogger:
    level: INFO
    handlers: [console, info_file_handler]
    qualname: InfoLogger
    propagate: yes

  DebugLogger:
    level: DEBUG
    handlers: [console, debug_file_handler]
    qualname: DebugLogger
    propagate: yes

handlers:
  console:
    level: NOTSET
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: standard

  info_file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: info.log
  #  maxBytes: 10485760 # 10MB
  #  backupCount: 20
  #  encoding: utf8
  #
  #error_file_handler:
  #  class: logging.handlers.RotatingFileHandler
  #  level: ERROR
  #  formatter: error
  #  filename: errors.log
  #  maxBytes: 10485760 # 10MB
  #  backupCount: 20
  #  encoding: utf8
  #
  debug_file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: debug.log
    # maxBytes: 10485760 # 10MB
    # backupCount: 20
    # encoding: utf8
  #
  #critical_file_handler:
  #  class: logging.handlers.RotatingFileHandler
  #  level: CRITICAL
  #  formatter: standard
  #  filename: critical.log
  #  maxBytes: 10485760 # 10MB
  #  backupCount: 20
  #  encoding: utf8
  #
  #warn_file_handler:
  #  class: logging.handlers.RotatingFileHandler
  #  level: WARN
  #  formatter: standard
  #  filename: warn.log
  #  maxBytes: 10485760 # 10MB
  #  backupCount: 20
  #  encoding: utf8

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  error:
    format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"
